@startuml

state ArenaOn {
  ArenaOn : entry / enableCommandPollingTimer()
  ArenaOn : exit / disableCommandPollingTimer()
  ArenaOn : COMMAND_POLLING_TIMEOUT / pollCommand()
  state DisplayOn {
    DisplayOn : entry / enableFrameRateTimer()
    DisplayOn : exit / disableFrameRateTimer()
    state WaitingToShowFrame {
    }
    state ShowingFrame {
      ShowingFrame : BEGIN_TRANSFER_FRAME /
      ShowingFrame : END_TRANSFER_FRAME /
      state AllOn {
      }
      state StreamingFrame {
      }
      state RunningTrial {
      }
    }
    DisplayOn --> AllOn : ALL_ON
    DisplayOn --> StreamingFrame : STREAM_FRAME
    DisplayOn --> RunningTrial : START_TRIAL
    WaitingToShowFrame --> ShowingFrame : FRAME_RATE_TIMER_EXPIRE
  }
  state DisplayOff {
  }
}
[*] --> ArenaOn : POWER_SWITCH_ON
ArenaOn --> ArenaOn : RESET
ArenaOn --> [*] : POWER_SWITCH_OFF

@enduml
